- [Tuning Hyperparameters Under 10 Minutes (LGBM)](https://www.kaggle.com/code/somang1418/tuning-hyperparameters-under-10-minutes-lgbm/notebook)
- [Advanced tour of the Bayesian Optimization package](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb)
